name: "°dentity"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  odentity-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - name: push o-textile-hub
        id: otextilehub
        uses: textileio/github-action-buckets@v20
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "o-website"
          thread: "bafk3hjqnsapk7bbedswqq5pfhi3jue3kq7h6wnhgd5o7eedlrkroeva"
          path: "src/"
      - run: echo "bucket - ${{ steps.otextilehub.outputs.key }}"
      - run: echo "ipfs - ${{ steps.otextilehub.outputs.ipfs }}"
      - run: echo "ipfs link - ${{ steps.otextilehub.outputs.ipfsUrl }}"
      - run: echo "ipns - ${{ steps.otextilehub.outputs.ipns }}"
      - run: echo "ipns link - ${{ steps.otextilehub.outputs.ipnsUrl }}"
      - run: echo "hub - ${{ steps.otextilehub.outputs.hub }}"
      - run: echo "www - ${{ steps.otextilehub.outputs.www }}"
